# Do not build branches of the form "pr/*". By prefixing pull requests coming
# from branches inside the repository with pr/, this avoids building both the
# branch push _and_ the pull request.
branches:
  except: /pr\/.*/

os:
  - linux

language: csharp

solution: ./nanoFramework.Tools.Hex2Dfu/nanoFramework.Tools.Hex2Dfu.sln

install:
  - nuget restore ./nanoFramework.Tools.Hex2Dfu/nanoFramework.Tools.Hex2Dfu.sln

script:
  - msbuild /p:Configuration=Release ./nanoFramework.Tools.Hex2Dfu/nanoFramework.Tools.Hex2Dfu.sln

deploy:
  provider: releases
  api_key: 
    secure: "KuQi9IqB1De7eicwGRwWauolYqRdypE9HzHctdmMO9raVRPj1HhuVz245BTnr7YzHDNlheNMOBJ0iUv5Anzz8yxuYA0yGyw2mlfi0jtBmN1RdDnzRufMD7jDXEtYKP/I9vlg6lV43lENHFVJzpNR1oQ4wsSdQsr1BgRBkyrBcUzSsOd27Tq4MsIuyBA+eMxKnBK3BT+0kLrHKj/qwUnDOa9modK3HlrNHl7yoZ8C23BDaS6PLm2IgHNPjfexdCOGzvsxelSHfEh7jOUMD4CnJzd5ZMLPsdocV38BMP0iuSf8BKSR28N9uRBb8IUhuPTHlj2ogCEpVvk2BEK6mdZZxt8SFeDBoJQsk3mMRy1dLtsvqX19O3C5uY3H7WQNCbGFw3+SUmSuXXiqL5n1oaffq9IXTs1atZaKrX49T7cB5fnxkmfZZdcldGsIPFmBHtIph7oeUegM9AIBlP442X2DprVIKI6HC+T2H3zN9ltgA8UwAClNCA9dVUCtQmzM4CGqxyM95j9w6V6iR2SMQYZil2+B+QCoHYth1igeP+vVHz4ZvX3+ux3UptW0YTFABef2YmY8t3FFWlhevYsFae7lS9YwMUk+m9b7SpzwHFO2m6AFOxlGmXjNFHt9L4ldFb0+5YyAQ8r7gWjGOnSEFiZNcyrFkC2JduaNzKkPcIaLTtI="
  file: ./nanoFramework.Tools.Hex2Dfu/bin/Release/hex2dfu.exe
  skip_cleanup: true
  on:
    tags: true
