version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
clone_depth: 1

build_script:
- ps: >-
    nuget restore nanoFramework.Tools.Hex2Dfu\nanoFramework.Tools.Hex2Dfu.sln

    msbuild nanoFramework.Tools.Hex2Dfu\nanoFramework.Tools.Hex2Dfu.sln /unsafe /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
